### ISSUE TITLE
Can you make mod for Captain to have infinite times to place beacons but with cooldown?

### ISSUE THREAD

**Issue by ghost** [Charzard4261/Captain-Abilities-Offworld#1]
:D

**Comment by Charzard4261** [comment]
Sorry, this project is meant to solely allow the Captain to use his abilities offworld without any extra bloat or other game changing tweaks. As such, this falls outside of the scope of it.

**Comment by ghost** [comment]
I'm about another mod

**Comment by Charzard4261** [comment]
Ah, misread, but issues is not really a place to put new project requests lol. Sorry not planning on making any more RoR2 mods unless something else that irritates me pops up.
